name: actions-trial
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: chmod +x gcd.sh
      - run: chmod +x test_scripts/test.sh
      - run: bash test_scripts/test.sh

